```yaml
on:
  workflow_run:
    workflows: ["Threadline CI"]
    types:
      - completed


jobs:

  deploy:
    # Запускаем deploy только если Threadline CI завершился успешно
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # GitHub запускает этот job на своей виртуальной машине
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to VPS
        # GitHub Action, который подключается к VPS по SSH
        uses: appleboy/ssh-action@v1.2.2

        with:
          # IP-адрес VPS из GitHub Secrets
          host: ${{ secrets.VPS_HOST }}

          # Пользователь VPS из GitHub Secrets
          username: ${{ secrets.VPS_USER }}

          # Приватный SSH-ключ из GitHub Secrets
          key: ${{ secrets.VPS_SSH_KEY }}

  
          port: 6767

          script: |

            # Переходим в папку приложения
            cd /var/www/second-app

            # Забираем последние изменения из Git
            git pull origin master

            # Скачиваем новые Docker images
            docker compose -f docker-compose.prod.yml pull

            # Перезапускаем контейнеры
            docker compose -f docker-compose.prod.yml up -d
```
